[package]
name = "gtk-block-screen"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"
publish = false

[dependencies]
gdk = "0.15.4"
glib = "0.15.12"
gtk = "0.15.5"
cairo-rs = "0.15.12"
