[package]
name = "gtk-block-screen"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"
publish = false

[dependencies]
gdk = "0.13.0"
glib = "0.10.0"
gtk = "0.9.0"
cairo-rs = "0.9.0"
